import {test,expect} from '@playwright/test';
import {installApiFixture} from './support/api-fixture';
test.beforeEach(async({page})=>{await installApiFixture(page);});
test('guides keep report interactive; zoom persists; seven curves and eight charts toggle',async({page})=>{
 await page.setViewportSize({width:1440,height:1000});await page.goto('login/');await page.getByRole('button',{name:'Hướng dẫn',exact:true}).click();const guide=page.getByRole('complementary',{name:'Hướng dẫn màn hình hiện tại'});await expect(guide).toBeVisible();await page.getByLabel('ID học sinh').fill('HV000123');await page.locator('input[autocomplete="current-password"]').fill('Demo123!');await page.getByRole('button',{name:'Đăng nhập',exact:true}).click();await expect(page.getByRole('heading',{name:'Tổng quan kết quả Unit 3'})).toBeVisible();await expect(guide.getByRole('heading',{name:'Báo cáo học tập',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Thu nhỏ giao diện',exact:true}).click();await expect(page.getByTestId('application-scale')).toHaveAttribute('data-zoom','85');await page.getByRole('tab',{name:'Unit 1',exact:true}).click();await expect(page.getByRole('heading',{name:'Tổng quan kết quả Unit 1'})).toBeVisible();await page.getByRole('tab',{name:'Unit 3',exact:true}).click();
 await page.getByTestId('skills-chart').scrollIntoViewIfNeeded();await expect(page.getByTestId('skills-chart').locator('.recharts-line-curve')).toHaveCount(7);await page.getByRole('button',{name:'Ẩn Vocabulary',exact:true}).click();await expect(page.getByTestId('skills-chart').locator('.recharts-line-curve')).toHaveCount(6);await page.getByRole('button',{name:'Hiện Vocabulary',exact:true}).click();await expect(page.getByTestId('skills-chart').locator('.recharts-line-curve')).toHaveCount(7);
 await page.getByRole('heading',{name:'Thay đổi điểm theo từng kỹ năng qua các Unit'}).scrollIntoViewIfNeeded();await expect(page.getByTestId('change-chart')).toHaveCount(8);await page.getByRole('button',{name:'Ẩn Tổng điểm · thay đổi',exact:true}).click();await expect(page.getByTestId('change-chart')).toHaveCount(7);await page.getByRole('button',{name:'Hiện tất cả biểu đồ thay đổi',exact:true}).click();await expect(page.getByTestId('change-chart')).toHaveCount(8);
 await guide.getByRole('button',{name:'Ẩn hướng dẫn',exact:true}).click();await expect(guide).not.toBeVisible();await page.reload();await expect(page.getByTestId('application-scale')).toHaveAttribute('data-zoom','85');
});
test('mobile dark guide has independent scroll and supports chart/class controls',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.emulateMedia({colorScheme:'dark'});await page.goto('auth/link/#code=valid-test-code');await expect(page.getByRole('heading',{name:'Tổng quan kết quả Unit 3'})).toBeVisible();await page.getByRole('button',{name:'Hướng dẫn',exact:true}).click();const guide=page.getByRole('complementary',{name:'Hướng dẫn màn hình hiện tại'});await expect(guide).toBeVisible();await page.getByRole('button',{name:'Thu nhỏ giao diện',exact:true}).click();await page.getByRole('combobox',{name:'Lớp học',exact:true}).click();await page.getByRole('option',{name:'Juniors 02',exact:true}).click();await expect(page.getByText('Lớp này chưa có Unit học tập.',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await guide.getByRole('button',{name:'Ẩn hướng dẫn',exact:true}).click();await page.getByRole('button',{name:'Đặt lại kích thước 100%',exact:true}).click();await expect(page.getByTestId('application-scale')).toHaveAttribute('data-zoom','100');
});
