export interface Guide { title: string; intro: string; steps: { title: string; text: string[]; illustration?: string }[] }
const step = (title: string, text: string[], illustration?: string) => ({ title, text, illustration });
const login: Guide = { title: "Đăng nhập", intro: "Truy cập đúng tài khoản do trung tâm cấp; giao diện sáng/tối và thu/phóng có thể đổi ngay tại đây.", steps: [step("ID và mật khẩu", ["Nhập ID đăng nhập và mật khẩu, dùng nút Hiện/Ẩn để kiểm tra ký tự. Nút Đăng nhập hiển thị trạng thái đang xử lý; lỗi nằm ngay trong form.", "Không lưu mật khẩu trong trình duyệt. Khi hết phiên, đăng nhập lại để tiếp tục; dữ liệu đã lưu vẫn được giữ."], "form"), step("Liên kết đăng nhập", ["Mở link do trung tâm cấp. Mã chỉ dùng một lần và có thời hạn; mã sai/hết hạn/đã dùng có nút quay lại đăng nhập.", "Đăng xuất kết thúc phiên hiện tại. Thời gian đăng nhập và thông tin thiết bị/IP phục vụ bảo mật tài khoản."])] };
const report: Guide = { title: "Báo cáo học tập", intro: "Đọc kết quả đánh giá theo Unit, đối chiếu các kỹ năng và nhận xét để biết phần cần luyện tập. Tỷ lệ điểm khác tiến độ hoàn thành khóa học.", steps: [step("Chọn lớp, học sinh và Unit", ["Chọn lớp để xem đúng lịch sử học tập. Staff chọn thêm học sinh; tab Unit dùng dữ liệu đã công bố cho học sinh đó.", "Mặc định mở Unit có thứ tự cao nhất. Đổi lớp/học sinh sẽ chọn lại Unit, tránh nhầm báo cáo. Nếu chưa công bố, màn hình báo chưa có dữ liệu."], "report"), step("Tổng quan kết quả", ["Mỗi ô ghi điểm đạt / điểm tối đa và tỷ lệ phần trăm của kỹ năng. Tổng điểm chia tổng điểm tối đa, không lấy trung bình phần trăm các kỹ năng.", "Dấu — là chưa có dữ liệu; số 0 là một kết quả đã nhập. Ngày kiểm tra thiếu được giữ là chưa có."], "report"), step("Đường kỹ năng và bảng Unit", ["Mỗi màu là một kỹ năng; trục ngang là các Unit, trục dọc là tỷ lệ điểm. Chạm hoặc rê lên node để đọc chi tiết. Đường cong đi qua đúng điểm; chỗ chưa có dữ liệu không được nối thay.", "Bấm tên kỹ năng để ẩn/hiện, hoặc Hiện tất cả để khôi phục. Chỉ thay cách xem biểu đồ, bảng và dữ liệu gốc giữ nguyên.", "Bảng điểm theo Unit giúp so sánh số liệu chính xác; trên điện thoại có thể cuộn ngang."], "chart"), step("Biểu đồ thay đổi", ["Mỗi biểu đồ so sánh hai Unit liên tiếp. Xanh là tăng, hồng là giảm; dấu +/− và tooltip thể hiện chênh lệch theo điểm phần trăm.", "Ví dụ 60% → 70% là +10 điểm phần trăm. Có thể ẩn/hiện từng biểu đồ kỹ năng hoặc tổng điểm; thiếu một mốc thì chưa tính chênh lệch."], "chart"), step("Nhận xét và lời khuyên", ["Đọc nhận xét theo kỹ năng, nhận xét tổng thể và các lời khuyên. Những phần chưa có được ghi rõ; không thay bằng nhận định tự động.", "Staff: quản lý xem báo cáo; giảng viên đang phụ trách lớp ACTIVE có thể bấm Sửa nhận xét. Form chỉ đổi nhận xét, giữ điểm/schema và lời khuyên. Lưu thành công cập nhật báo cáo học sinh và nguồn bài đánh giá khi còn khớp.", "Nếu báo xung đột, giữ nội dung đang nhập và tải phiên bản mới trước khi quyết định lưu lại. Đổi học sinh/Unit khi chưa lưu cần xác nhận."], "form")] };
const materials: Guide = { title: "Thread học tập", intro: "Đọc bài đăng của giảng viên theo lớp, xem tài liệu và trao đổi trong bình luận.", steps: [step("Thread và tài liệu", ["Mặc định mở tab Thread, mỗi bài có tác giả, người đăng, thời gian, hướng dẫn và tài liệu. Chọn tab Tài liệu để lọc bài tài liệu theo phiên; tab Báo cáo kết quả giữ điểm và nhận xét theo Unit.", "Thông tin giảng viên phụ trách có email/số điện thoại nếu trung tâm đã cập nhật. Chọn lớp ở trang chính để xem đúng nội dung."], "report"), step("Tương tác và bình luận", ["Chọn Thích/Yêu thích/Chúc mừng; bấm lại để bỏ, chọn kiểu khác để đổi. Mở Bình luận để viết, trả lời và sửa bình luận của mình.", "Bấm Đính kèm để tải ảnh, PDF, audio, video hoặc tài liệu. Ảnh trên 20 MB được nén trước khi tải; ổ nhận do quản lý cấu hình. File đã tải chưa được công khai cho đến khi gửi bình luận.", "Đổi trang khi còn bản nháp sẽ cần xác nhận; chuyển tab vẫn giữ bản nháp."], "form"), step("Xem và tải file", ["Bấm tên/thumbnail để mở trình xem. PDF có lật trang/cuộn dọc, zoom và toàn màn hình; audio có tua/tốc độ. Tải xuống yêu cầu quyền truy cập của tài khoản hiện tại.", "Khi không còn hoạt động trong lớp, tài liệu và file bình luận của lớp sẽ không truy cập được. Nếu lỗi, bấm Thử lại; không cần chờ hệ thống tự tải theo chu kỳ."], "form")] };
export function pageGuide(pathname: string, entity: string | null, workspace?: string | null): Guide {
  void entity; void workspace;
  if (pathname.includes("/materials")) return materials;
  if (pathname.includes("/home") || pathname.includes("/dashboard")) return { ...report, steps: report.steps.map((s) => s.title === "Chọn lớp, học sinh và Unit" ? { ...s, title: "Chọn lớp và Unit", text: ["Chọn lớp đã học để xem lịch sử của chính tài khoản. Ba tab: Thread mặc định để trao đổi, Tài liệu lọc theo phiên học, Báo cáo kết quả để xem điểm. Trong báo cáo, Unit mặc định có thứ tự cao nhất của lớp.", "Đổi lớp sẽ chọn lại Unit; khi chưa có lớp, Unit hoặc báo cáo, màn hình hiển thị trạng thái trống."] } : s.title === "Nhận xét và lời khuyên" ? { ...s, text: [s.text[0], "Chọn tab Thread để trao đổi, Tài liệu để lọc theo phiên, Báo cáo kết quả để đọc điểm; học sinh xem nhận xét và kết quả, không sửa điểm."] } : s) };
  return login;
}
