export interface Guide { title: string; intro: string; steps: { title: string; text: string[]; illustration?: string }[] }
const step = (title: string, text: string[], illustration?: string) => ({ title, text, illustration });
const login: Guide = { title: "Đăng nhập", intro: "Truy cập đúng tài khoản do trung tâm cấp; giao diện sáng/tối và thu/phóng có thể đổi ngay tại đây.", steps: [step("ID và mật khẩu", ["Nhập ID đăng nhập và mật khẩu, dùng nút Hiện/Ẩn để kiểm tra ký tự. Nút Đăng nhập hiển thị trạng thái đang xử lý; lỗi nằm ngay trong form.", "Không lưu mật khẩu trong trình duyệt. Khi hết phiên, đăng nhập lại để tiếp tục; dữ liệu đã lưu vẫn được giữ."], "form"), step("Liên kết đăng nhập", ["Mở link do trung tâm cấp. Mã chỉ dùng một lần và có thời hạn; mã sai/hết hạn/đã dùng có nút quay lại đăng nhập.", "Đăng xuất kết thúc phiên hiện tại. Thời gian đăng nhập và thông tin thiết bị/IP phục vụ bảo mật tài khoản."])] };
const report: Guide = { title: "Báo cáo học tập", intro: "Đọc kết quả đánh giá theo Unit, đối chiếu các kỹ năng và nhận xét để biết phần cần luyện tập. Tỷ lệ điểm khác tiến độ hoàn thành khóa học.", steps: [step("Chọn lớp, học sinh và Unit", ["Chọn lớp để xem đúng lịch sử học tập. Staff chọn thêm học sinh; tab Unit dùng dữ liệu đã công bố cho học sinh đó.", "Mặc định mở Unit có thứ tự cao nhất. Đổi lớp/học sinh sẽ chọn lại Unit, tránh nhầm báo cáo. Nếu chưa công bố, màn hình báo chưa có dữ liệu."], "report"), step("Tổng quan kết quả", ["Mỗi ô ghi điểm đạt / điểm tối đa và tỷ lệ phần trăm của kỹ năng. Tổng điểm chia tổng điểm tối đa, không lấy trung bình phần trăm các kỹ năng.", "Dấu — là chưa có dữ liệu; số 0 là một kết quả đã nhập. Ngày kiểm tra thiếu được giữ là chưa có."], "report"), step("Đường kỹ năng và bảng Unit", ["Mỗi màu là một kỹ năng; trục ngang là các Unit, trục dọc là tỷ lệ điểm. Chạm hoặc rê lên node để đọc chi tiết. Đường cong đi qua đúng điểm; chỗ chưa có dữ liệu không được nối thay.", "Bấm tên kỹ năng để ẩn/hiện, hoặc Hiện tất cả để khôi phục. Chỉ thay cách xem biểu đồ, bảng và dữ liệu gốc giữ nguyên.", "Bảng điểm theo Unit giúp so sánh số liệu chính xác; trên điện thoại có thể cuộn ngang."], "chart"), step("Biểu đồ thay đổi", ["Mỗi biểu đồ so sánh hai Unit liên tiếp. Xanh là tăng, hồng là giảm; dấu +/− và tooltip thể hiện chênh lệch theo điểm phần trăm.", "Ví dụ 60% → 70% là +10 điểm phần trăm. Có thể ẩn/hiện từng biểu đồ kỹ năng hoặc tổng điểm; thiếu một mốc thì chưa tính chênh lệch."], "chart"), step("Nhận xét và lời khuyên", ["Đọc nhận xét theo kỹ năng, nhận xét tổng thể và các lời khuyên. Những phần chưa có được ghi rõ; không thay bằng nhận định tự động.", "Staff: quản lý xem báo cáo; giảng viên đang phụ trách lớp ACTIVE có thể bấm Sửa nhận xét. Form chỉ đổi nhận xét, giữ điểm/schema và lời khuyên. Lưu thành công cập nhật báo cáo học sinh và nguồn bài đánh giá khi còn khớp.", "Nếu báo xung đột, giữ nội dung đang nhập và tải phiên bản mới trước khi quyết định lưu lại. Đổi học sinh/Unit khi chưa lưu cần xác nhận."], "form")] };
const materials: Guide = { title: "Tài liệu học tập", intro: "Tài liệu thuộc lớp đang chọn, hỗ trợ PDF, audio, video và liên kết.", steps: [step("Kiểm tra lớp", ["Tiêu đề cho biết lớp của danh sách. Dùng nút quay lại báo cáo để đổi lớp; tài liệu lớp khác không được trộn vào đây."], "report"), step("Mở hoặc phát", ["Mỗi dòng có tên và loại tài liệu; dung lượng/thời lượng chỉ hiện khi đã có dữ liệu.", "Bấm Mở/Phát để xin quyền truy cập rồi mở tài liệu. Liên kết có thời hạn; khi hết hạn, bấm lại để lấy quyền mới. Trình duyệt có thể yêu cầu cho phép mở tab."], "form"), step("Trạng thái danh sách", ["Đang tải: chờ danh sách. Chưa có tài liệu: trung tâm chưa công bố. Có lỗi: dùng Thử lại, dữ liệu báo cáo vẫn được giữ."])] };
export function pageGuide(pathname: string, entity: string | null, workspace?: string | null): Guide {
  void entity; void workspace;
  if (pathname.includes("/materials")) return materials;
  if (pathname.includes("/home") || pathname.includes("/dashboard")) return { ...report, steps: report.steps.map((s) => s.title === "Chọn lớp, học sinh và Unit" ? { ...s, title: "Chọn lớp và Unit", text: ["Chọn lớp đã học để xem lịch sử của chính tài khoản. Tab Unit lấy từ API của lớp đang chọn, mặc định Unit có thứ tự cao nhất.", "Đổi lớp sẽ chọn lại Unit; khi chưa có lớp, Unit hoặc báo cáo, màn hình hiển thị trạng thái trống."] } : s.title === "Nhận xét và lời khuyên" ? { ...s, text: [s.text[0], "Tài liệu học tập nằm ngay dưới tab Unit. Mở để luyện tập theo lớp hiện tại; học sinh xem nhận xét và kết quả, không sửa điểm."] } : s) };
  return login;
}
